"""add_clinical_validation_table

Revision ID: 9825270bad6e
Revises: c1d4a9f27b83
Create Date: 2026-09-04 17:17:37.586333
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9825270bad6e'
down_revision: str | None = 'c1d4a9f27b83'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_validations',
    sa.Column('screening_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=False),
    sa.Column('reviewer_role', sa.String(length=255), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('formatted_timestamp', sa.String(length=128), nullable=False),
    sa.Column('original_ai_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('confirmed', 'needs_review')", name=op.f('ck_clinical_validations_status')),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('fk_clinical_validations_screening_id_screenings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_validations')),
    sa.UniqueConstraint('screening_id', name='uq_clinical_validations_screening')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinical_validations')
    # ### end Alembic commands ###
