"""initial schema

Revision ID: f421071622af
Revises: 6da5a9a72215
Create Date: 2026-07-29 01:40:03.464219
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import hemavision_api.core.db

revision: str = "f421071622af"
down_revision: str | None = "6da5a9a72215"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consent_documents",
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_documents")),
        sa.UniqueConstraint("version", "locale", name="uq_consent_documents_version"),
    )
    op.create_table(
        "organizations",
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("region_code", sa.String(length=32), nullable=True),
        sa.Column("path", hemavision_api.core.db.Ltree(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('dinkes_prov', 'dinkes_kab', 'puskesmas', 'posyandu', 'sekolah', 'rs')",
            name=op.f("ck_organizations_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["organizations.id"],
            name=op.f("fk_organizations_parent_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("path", name=op.f("uq_organizations_path")),
    )
    op.create_index(
        "ix_organizations_path", "organizations", ["path"], unique=False, postgresql_using="gist"
    )
    op.create_table(
        "policy_versions",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('fusion', 'threshold', 'who_cutoff')", name=op.f("ck_policy_versions_kind")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_versions")),
        sa.UniqueConstraint("kind", "version", name="uq_policy_versions_kind_version"),
    )
    op.create_table(
        "users",
        sa.Column("identity_provider_uid", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'suspended')", name=op.f("ck_users_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("identity_provider_uid", name=op.f("uq_users_identity_provider_uid")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_organization_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_actor_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_events_actor_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("hash", name=op.f("uq_audit_events_hash")),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_idempotency_keys_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint("key", "organization_id", name="uq_idempotency_keys_key_org"),
    )
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('pasien', 'kader', 'bidan', 'dokter', 'admin_faskes', 'admin_dinkes', 'platform_admin')",
            name=op.f("ck_memberships_role"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "user_id", "organization_id", "role", name="uq_memberships_user_org_role"
        ),
    )
    op.create_table(
        "patients",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("nik_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("nik_hmac", sa.LargeBinary(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("sex", sa.String(), nullable=False),
        sa.Column("pregnancy_status", sa.String(), server_default="unknown", nullable=False),
        sa.Column("key_version", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pregnancy_status IN ('none', 'pregnant', 'unknown')",
            name=op.f("ck_patients_pregnancy_status"),
        ),
        sa.CheckConstraint("sex IN ('M', 'F')", name=op.f("ck_patients_sex")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_patients_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
        sa.UniqueConstraint("nik_hmac", name=op.f("uq_patients_nik_hmac")),
    )
    op.create_table(
        "consents",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signature_method", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["consent_documents.id"],
            name=op.f("fk_consents_document_id_consent_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_consents_patient_id_patients")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
    )
    op.create_table(
        "dsar_requests",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column(
            "requested_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("artifact_uri", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("kind IN ('export', 'erase')", name=op.f("ck_dsar_requests_kind")),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'failed')", name=op.f("ck_dsar_requests_status")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_dsar_requests_patient_id_patients")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dsar_requests")),
    )
    op.create_table(
        "emergency_access_grants",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_emergency_access_grants_approved_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_emergency_access_grants_patient_id_patients"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_emergency_access_grants_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emergency_access_grants")),
    )
    op.create_table(
        "patient_baselines",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("mean_hb", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("sd_hb", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("n_obs", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_patient_baselines_patient_id_patients")
        ),
        sa.PrimaryKeyConstraint("patient_id", name=op.f("pk_patient_baselines")),
    )
    op.create_table(
        "screenings",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("performed_by_user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'processing', 'completed', 'failed', 'inconclusive')",
            name=op.f("ck_screenings_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_screenings_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_screenings_patient_id_patients")
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["users.id"],
            name=op.f("fk_screenings_performed_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screenings")),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_screenings_org_idempotency_key"
        ),
    )
    op.create_table(
        "fused_results",
        sa.Column("screening_id", sa.UUID(), nullable=False),
        sa.Column("hb_gdl", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("probability", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("who_category", sa.String(length=16), nullable=False),
        sa.Column("contributing_sites", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("caveats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fusion_policy_version", sa.String(length=32), nullable=False),
        sa.Column("threshold_policy_version", sa.String(length=32), nullable=False),
        sa.Column("who_cutoff_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('anemic', 'non_anemic', 'inconclusive')",
            name=op.f("ck_fused_results_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["screening_id"],
            ["screenings.id"],
            name=op.f("fk_fused_results_screening_id_screenings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fused_results")),
        sa.UniqueConstraint("screening_id", name="uq_fused_results_screening"),
    )
    op.create_table(
        "job_failures",
        sa.Column("screening_id", sa.UUID(), nullable=True),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column(
            "occurred_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["screening_id"],
            ["screenings.id"],
            name=op.f("fk_job_failures_screening_id_screenings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_failures")),
    )
    op.create_table(
        "reference_measurements",
        sa.Column("screening_id", sa.UUID(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("hb_gdl", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("measured_by_user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "method IN ('hemocue', 'cbc')", name=op.f("ck_reference_measurements_method")
        ),
        sa.ForeignKeyConstraint(
            ["measured_by_user_id"],
            ["users.id"],
            name=op.f("fk_reference_measurements_measured_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["screening_id"],
            ["screenings.id"],
            name=op.f("fk_reference_measurements_screening_id_screenings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_measurements")),
    )
    op.create_table(
        "referrals",
        sa.Column("screening_id", sa.UUID(), nullable=False),
        sa.Column("urgency", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column("referred_to_org_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'closed')", name=op.f("ck_referrals_status")),
        sa.CheckConstraint("urgency IN ('routine', 'urgent')", name=op.f("ck_referrals_urgency")),
        sa.ForeignKeyConstraint(
            ["referred_to_org_id"],
            ["organizations.id"],
            name=op.f("fk_referrals_referred_to_org_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["screening_id"], ["screenings.id"], name=op.f("fk_referrals_screening_id_screenings")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referrals")),
    )
    op.create_table(
        "screening_captures",
        sa.Column("screening_id", sa.UUID(), nullable=False),
        sa.Column("site", sa.String(length=16), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("roi_object_key", sa.Text(), nullable=True),
        sa.Column("raw_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "site IN ('conjunctiva', 'palm', 'nail')", name=op.f("ck_screening_captures_site")
        ),
        sa.ForeignKeyConstraint(
            ["screening_id"],
            ["screenings.id"],
            name=op.f("fk_screening_captures_screening_id_screenings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screening_captures")),
        sa.UniqueConstraint("screening_id", "site", name="uq_screening_captures_screening_site"),
    )
    op.create_table(
        "site_results",
        sa.Column("screening_id", sa.UUID(), nullable=False),
        sa.Column("site", sa.String(length=16), nullable=False),
        sa.Column("passed_qc", sa.Boolean(), nullable=True),
        sa.Column("reasons", sa.ARRAY(sa.String(length=32)), server_default="{}", nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hb_gdl", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("anemic_probability", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("model_severity", sa.String(length=16), nullable=True),
        sa.Column("handcrafted_features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "inference_status", sa.String(length=16), server_default="pending", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "inference_status IN ('pending', 'completed', 'failed')",
            name=op.f("ck_site_results_inference_status"),
        ),
        sa.CheckConstraint(
            "site IN ('conjunctiva', 'palm', 'nail')", name=op.f("ck_site_results_site")
        ),
        sa.ForeignKeyConstraint(
            ["screening_id"],
            ["screenings.id"],
            name=op.f("fk_site_results_screening_id_screenings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_results")),
        sa.UniqueConstraint("screening_id", "site", name="uq_site_results_screening_site"),
    )
    op.create_table(
        "follow_ups",
        sa.Column("referral_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["referral_id"], ["referrals.id"], name=op.f("fk_follow_ups_referral_id_referrals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_follow_ups")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("follow_ups")
    op.drop_table("site_results")
    op.drop_table("screening_captures")
    op.drop_table("referrals")
    op.drop_table("reference_measurements")
    op.drop_table("job_failures")
    op.drop_table("fused_results")
    op.drop_table("screenings")
    op.drop_table("patient_baselines")
    op.drop_table("emergency_access_grants")
    op.drop_table("dsar_requests")
    op.drop_table("consents")
    op.drop_table("patients")
    op.drop_table("memberships")
    op.drop_table("idempotency_keys")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("policy_versions")
    op.drop_index("ix_organizations_path", table_name="organizations", postgresql_using="gist")
    op.drop_table("organizations")
    op.drop_table("consent_documents")
    # ### end Alembic commands ###
