export const ROUTES = {
  PUBLIC: {
    HOME: "/",
    LOGIN_NAKES: "/login-nakes",
    LOGIN_PASIEN: "/login-pasien",
    REGISTER: "/register",
    OFFLINE: "/offline",
  },
  NAKES: {
    DASHBOARD: "/nakes",
    PASIEN_LIST: "/nakes/pasien",
    PASIEN_BARU: "/nakes/pasien/baru",
    PASIEN_DETAIL: (id: string) => `/nakes/pasien/${id}`,
    SKRINING_OVERVIEW: "/nakes/skrining",
    SKRINING_BARU: "/nakes/skrining/baru",
    SKRINING_PERIKSA_KAMERA: "/nakes/skrining/periksa-kamera",
    HASIL: "/nakes/hasil",
    MONITORING: "/nakes/monitoring",
    LAPORAN: "/nakes/laporan",
    PERMINTAAN: "/nakes/permintaan",
    PANDUAN: (sessionId: string) => `/nakes/skrining/panduan/${sessionId}`,
  },
  PATIENT: {
    ROOT: "/pasien",
    BERANDA: "/pasien/beranda",
    HOME: "/pasien",
    HASIL: "/pasien/hasil",
    HASIL_DETAIL: "/pasien/hasil/detail",
    HASIL_PENJELASAN: "/pasien/hasil/penjelasan",
    TINDAK_LANJUT: "/pasien/tindak-lanjut",
    RIWAYAT: "/pasien/riwayat",
    EDUKASI: "/pasien/edukasi",
    EDUKASI_DETAIL: "/pasien/edukasi/detail",
    PROFIL: "/pasien/profil",
    PROFIL_LENGKAPI: "/pasien/profil/lengkapi",
    SKRINING: "/pasien/skrining",
    SKRINING_KONDISI: "/pasien/skrining/kondisi",
    SKRINING_GEJALA: "/pasien/skrining/gejala",
    SKRINING_PERSIAPAN: "/pasien/skrining/persiapan",
    SKRINING_PERIKSA_KAMERA: "/pasien/skrining/periksa-kamera",
    SKRINING_CAPTURE: "/pasien/skrining/capture",
    SKRINING_TINJAU: "/pasien/skrining/tinjau",
    SKRINING_PROSES: "/pasien/skrining/proses",
    SKRINING_SELESAI: "/pasien/skrining/selesai",
    SKRINING_BANTUAN: "/pasien/skrining/bantuan",
  },
  CAPTURE: {
    SESSION: (sessionId: string) => `/capture/${sessionId}`,
  },
};
